name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    permissions: write-all
    name: Test
    runs-on: ubuntu-latest
    container: docker.io/library/golang:1.22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...